#!/usr/bin/env bash

# Rudimentary safety check
[[ ! -f "tools/build" ]] && echo 'Please run this from package root!' && return 1;

# Output.
echo 'Starting full build...'

# Run through full build flow.
./tools/clean &&
./tools/svg-optimize &&
./tools/svg-to-php &&
./tools/svg-to-sprite &&
./tools/svg-to-font.js &&
./tools/svg-to-react-data.js &&
./tools/build-react &&
echo 'Build complete.' ||
echo 'Build failure!'
