#!/usr/bin/env bash

# Rudimentary safety check.
[[ ! -f "tools/build-react" ]] && echo 'Please run this from package root!' && return 1;

# Define some paths.
src_react_dir=src/react
src_css_dir=src/css
dest_react_dir=build/react

# Make dir if it doesn't exist.
mkdir -p "$dest_react_dir"

# Copy source JSX as well.
cp "$src_react_dir"/*.jsx "$dest_react_dir"

# JSX -> JS
npx babel --quiet --presets @babel/preset-env,@babel/preset-react,minify --out-dir "$dest_react_dir" "$dest_react_dir"

# Copy example CSS.
cp "$src_css_dir"/example.css "$dest_react_dir"

# Output.
echo "Created React files in '$dest_react_dir'."
