#!/usr/bin/env bash

# Rudimentary safety check.
[[ ! -f "tools/svg-to-sprite" ]] && echo 'Please run this from package root!' && return 1;

# Define some paths.
src_svg_dir=build/svg-clean
src_sprite_dir=src/svg-sprite
src_css_dir=src/css
dest_sprite_dir=build/svg-sprite
dest_sprite_filename="$dest_sprite_dir"/social-logos.svg

# Make dir if it doesn't exist.
mkdir -p "$dest_sprite_dir"

# Generate SVG sprite file.
npx svgstore -o "$dest_sprite_filename" --inline "$src_svg_dir"/*.svg

# Make SVG more conformant.
sed -E -i.bak 's|<svg><defs/>|<svg xmlns="http://www.w3.org/2000/svg">|' "$dest_sprite_filename" && rm "$dest_sprite_filename.bak"

# Copy example files.
cp "$src_sprite_dir"/example.html "$dest_sprite_dir"
cp "$src_css_dir"/example.css "$dest_sprite_dir"

# Inject SVG into example file.
sed -i.bak "s|{{SVG_HERE}}|$(cat "$dest_sprite_filename")|" "$dest_sprite_dir/example.html" && rm "$dest_sprite_dir/example.html.bak"

# Output.
echo "Created SVG sprite file in '$dest_sprite_dir'."
